Repository 31th-SOPKATHON-8/AOS, pull requests merged in 2022-11, with the labels that each got.

#2 #1 [feat] 프로젝트 기초세팅
  .idea/.gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/sopt/sopkathon8aos/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/sopkathon8aos/SoptApplication.kt
  app/src/main/java/com/sopt/sopkathon8aos/data/repository/HomeRepository.kt
  app/src/main/java/com/sopt/sopkathon8aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/sopt/sopkathon8aos/data/service/HomeService.kt
  app/src/main/java/com/sopt/sopkathon8aos/data/source/local/LocalPrefDataSource.kt
  app/src/main/java/com/sopt/sopkathon8aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/sopt/sopkathon8aos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/sopkathon8aos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/sopkathon8aos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/sopkathon8aos/di/SharedPrefModule.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/sopkathon8aos/util/binding/BindingActivity.kt
  app/src/main/java/com/sopt/sopkathon8aos/util/binding/BindingAdapter.kt
  app/src/main/java/com/sopt/sopkathon8aos/util/binding/BindingFragment.kt
  app/src/main/java/com/sopt/sopkathon8aos/util/extensions/ContextExt.kt
  app/src/main/java/com/sopt/sopkathon8aos/util/extensions/ItemDiffCallback.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/sopt/sopkathon8aos/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: feat, pull request🔥, 영주🐼

#5 #4 [chore] 기초 뷰 추가 / 바텀 네비게이션 그래프 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/sopkathon8aos/presentation/brand/BrandActivity.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/favor/FavorFragment.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/posting/PostingActivity.kt
  app/src/main/java/com/sopt/sopkathon8aos/presentation/tutorial/TutorialActivity.kt
  app/src/main/res/layout/activity_brand.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_posting.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_favor.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/bottom_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: chore, pull request🔥, 준우🦦

#7 #3 [chore] 컬러, 텍스트 appearance 생성
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/font/pretendard_semibold.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
Labels: chore, pull request🔥, 영주🐼
